[local]
localhost

[mongodb]
mongodb-sg.uvraj.online

[redis]
redis.uvraj.online

[mysql]
mysql.uvraj.online

[rabbitmq]
rabbitmq.uvraj.online

[catalogue]
catalogue.uvraj.online

[user]
user.uvraj.online

[cart]
cart.uvraj.online

[shipping]
shipping.uvraj.online

[payment]
payment.uvraj.online

[frontend]
frontend.uvraj.online

